Project/owner/views.py
from Project import app
import matplotlib.pyplot as plt
from flask import render_template, Blueprint, flash
from flask_login import login_required, current_user
from functools import wraps
from datetime import datetime, timedelta
from Project.models import Movie, Screening, Sale
import matplotlib
matplotlib.use('Agg')
owner = Blueprint('owner', __name__)


def currency_format(value):
    value = float(value) / 100
    return "£{:,.2f}".format(value)


def make_autopct(values):
    def my_autopct(pct):
        total = sum(values)
        val = int(round(pct*total/100.0))
        return '{p:.2f}%  ({v})'.format(p=pct, v=currency_format(val))
    return my_autopct


def staff_manager_login_required(role, *args, **kwargs):
    def login_required(func):
        @wraps(func)
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated:
                return app.login_manager.unauthorized()
            elif current_user.is_staff != 1:
                flash("Restricted - Staff only", "danger")
                return app.login_manager.unauthorized()
            elif role == "manager":
                if current_user.is_manager != 1:
                    flash("Restricted - Managers only", "danger")
                    return app.login_manager.unauthorized()
            return func(*args, **kwargs)
        return decorated_view
    return login_required


@owner.route("/business/weekly_income")
@staff_manager_login_required("manager")
@login_required
def income():
    current_datetime = datetime.now()
    week_ago = current_datetime - timedelta(weeks=1)
    past_week_sales = Sale.query.filter(Sale.time_of_sale > week_ago).all()
    per_movie_sales = {}
    total_income = 0

    for sale in past_week_sales:
        total_income += sale.price

    for sale in past_week_sales:
        screening_id = sale.screening_id
        movie_id = Screening.query.filter_by(id=screening_id).first().movie_id
        name = Movie.query.filter_by(id=movie_id).first().name
        if name not in per_movie_sales:
            per_movie_sales[name] = sale.price
        else:
            per_movie_income = per_movie_sales[name] + sale.price
            per_movie_sales.update({name: per_movie_income})

    keys = per_movie_sales.keys()
    values = per_movie_sales.values()
    plt.tight_layout()
    plt.pie(values, labels=keys, wedgeprops={
        'edgecolor': 'black'}, shadow=True, autopct=make_autopct(values))
    plt.savefig("Project/static/weekly_income.png", bbox_inches="tight")
    plt.clf()
    return render_template("income.html", total_income=total_income, per_movie_sales=per_movie_sales, current_datetime=current_datetime)


@owner.route("/business/compare")
@staff_manager_login_required("manager")
@login_required
def compare_movies():
    current_datetime = datetime.now()
    current_datetime_string = str(current_datetime)
    week_ago = current_datetime - timedelta(weeks=1)
    movie_sales = {}
    past_week_sales = Sale.query.filter(Sale.time_of_sale > week_ago).all()
    for sale in past_week_sales:
        screening_id = sale.screening_id
        movie_id = Screening.query.filter_by(id=screening_id).first().movie_id
        name = Movie.query.filter_by(id=movie_id).first().name
        if name not in movie_sales:
            movie_sales[name] = 1
        else:
            sold = movie_sales[name] + 1
            movie_sales.update({name: sold})

    movie = movie_sales.keys()
    sales = movie_sales.values()
    plt.bar(movie, sales)
    plt.savefig("Project/static/sales.png", bbox_inches="tight")
    plt.clf()
    return render_template("compare.html", current_datetime_string=current_datetime_string, current_datetime=current_datetime)

Project/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from Project import db, email, app
from Project.models import User, Ticket, Movie, Screening, Sale, CardDetails
from Project.users.forms import RegistrationForm, LoginForm, AddTicketForm, PickSeatForm, SearchForm
from Project.business.forms import AddCardPaymentForm
import qrcode
import json
from reportlab.pdfgen import canvas
from flask_mail import Message
import os

users = Blueprint("users", __name__)


def currency_format(value):
    value = float(value) / 100
    return "£{:,.2f}".format(value)


@users.route('/list', methods=['GET', 'POST'])
def display_movies():
    form = SearchForm()
    list_movies = Movie.query.all()
    list_screenings = Screening.query.all()
    if form.validate_on_submit():
        search = form.search.data
        list_movies = Movie.query.filter(Movie.name.like("%" + search + "%"))
        return render_template('list.html', list_movies=list_movies, list_screenings=list_screenings, form=form)
    return render_template('list.html', list_movies=list_movies, list_screenings=list_screenings, form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged out", "info")
    return redirect("/list")


@users.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        if form.password.data == form.confirm_password.data:
            email = form.email.data
            email_exists = User.query.filter_by(
                email=email).first() is not None
            if email_exists:
                flash("That email is already used for another account", "danger")
            username = form.username.data
            username_exists = User.query.filter_by(
                username=username).first() is not None
            if username_exists:
                flash("That username is already used for another account", "danger")
            if username_exists or email_exists:
                return render_template("register.html", form=form)

            user = User(email=form.email.data,
                        username=form.username.data,
                        password=form.password.data, is_staff=False, is_manager=False)
            db.session.add(user)
            db.session.commit()

            flash("You have been registered", "success")
            return redirect(url_for("users.login"))
        else:
            flash("Passwords did not match", "danger")
    return render_template("register.html", form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash("Logged in", "success")
            next = request.args.get('next')
            if next:
                return redirect(next)
            else:
                if current_user.is_staff:
                    return redirect(url_for("business.display_movies"))
                else:
                    return redirect(url_for("users.display_movies"))
        else:
            flash("Login error", "danger")
    return render_template("login.html", form=form)


@users.route('/buy_ticket_online/<int:screening_id>/<string:seat>', methods=['GET', 'POST'])
def buy_ticket(screening_id, seat):
    form = AddTicketForm()
    screening = Screening.query.get(screening_id)
    movie_id = Screening.query.with_entities(
        Screening.movie_id).filter_by(id=screening_id).first().movie_id
    movie = Movie.query.get(movie_id)
    price = movie.price_as_pence
    is_vip = 0
    if int(seat) >= 1 and int(seat) <= 20:
        is_vip = 1
        price += 200
    if form.validate_on_submit():
        age = form.age.data
        certificate = movie.certificate
        can_watch = True
        if ((certificate == "12" or certificate == "12A") and int(age) < 12):
            can_watch = False
        if(certificate == "15" and int(age) < 15):
            can_watch = False
        if(certificate == "18" and int(age) < 18):
            can_watch = False
        if can_watch:
            email = form.email.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            new_ticket = Ticket(screening_id, seat, email,
                                first_name, last_name, age)
            db.session.add(new_ticket)
            db.session.commit()

            has_discount = 0
            if (int(form.age.data) >= 64 or int(form.age.data) <= 10):
                has_discount = 1

            form.email.data = ""
            form.age.data = ""
            form.first_name.data = ""
            form.last_name.data = ""
            return redirect(url_for('.make_card_payment', screening_id=screening_id, seat=seat, has_discount=has_discount))
        else:
            flash('Too young to watch movie: minimum 13 required', "danger")

    return render_template('buy_ticket_online.html', form=form, movie=movie, price=price, screening=screening, is_vip=is_vip)


@users.route('/card_payment/<int:screening_id>/<string:seat>/<int:has_discount>', methods=['GET', 'POST'])
def make_card_payment(screening_id, seat, has_discount):
    form = AddCardPaymentForm()
    if current_user.is_authenticated:
        details = CardDetails.query.filter_by(
            user_id=current_user.id).first()
        if details:
            flash("Saved details entered", "info")
            form.name.data = details.name
            form.card_number.data = details.card_number
            form.expiration.data = details.expiration
            form.security_code.data = details.security_code
            form.address.data = details.address
            form.town_city.data = details.town_city
            form.postcode.data = details.postcode
            form.country.data = details.country
    if form.validate_on_submit():
        name = form.name.data
        card_number = form.card_number.data
        expiration = form.expiration.data
        security_code = form.security_code.data
        address = form.address.data
        town_city = form.town_city.data
        postcode = form.postcode.data
        country = form.country.data

        remember = form.remember_me.data
        if remember == True:
            new_details = CardDetails(current_user.id, card_number, name,
                                      expiration, security_code, address, town_city, postcode, country)
            db.session.add(new_details)
            db.session.commit()

        form.name.data = ""
        form.card_number.data = ""
        form.expiration.data = ""
        form.security_code.data = ""
        form.address.data = ""
        form.town_city.data = ""
        form.postcode.data = ""
        form.country.data = ""

        is_vip = False
        if int(seat) >= 0 and int(seat) <= 20:
            is_vip = True
        movie_id = Screening.query.with_entities(
            Screening.movie_id).filter_by(id=screening_id).first().movie_id
        price = int(Movie.query.with_entities(
            Movie.price_as_pence).filter_by(id=movie_id).first().price_as_pence)
        if is_vip:
            price += 200
        if has_discount == 1:
            price = int(price * 0.9)

        new_sale = Sale(screening_id, seat, price)

        db.session.add(new_sale)
        db.session.commit()
        return redirect(url_for("users.generate_pdf_send"))

    return render_template("card_payment.html", form=form)


@users.route("/ticket_qrcode_pdf_send")
def generate_pdf_send():
    last_ticket = (Ticket.query.order_by(Ticket.id.desc()).first())
    last_ticket_dict = (last_ticket.__dict__)

    last_ticket_dict.pop('_sa_instance_state')
    ticket_json = json.dumps(last_ticket_dict)

    qrcode_image = qrcode.make(ticket_json)
    image_path = "ticket_qr_" + str(last_ticket_dict["id"]) + ".png"
    qrcode_image.save(image_path)

    screening_id = Ticket.query.with_entities(
        Ticket.screening_id).order_by(Ticket.id.desc()).first().screening_id
    time = str(Screening.query.with_entities(
        Screening.time).filter_by(id=screening_id).first().time)
    date = str(Screening.query.with_entities(
        Screening.date).filter_by(id=screening_id).first().date)
    seat = (Ticket.query.with_entities(
        Ticket.seat).order_by(Ticket.id.desc()).first()).seat
    movie_id = Screening.query.with_entities(
        Screening.movie_id).filter_by(id=screening_id).first().movie_id
    certificate = str(Movie.query.with_entities(
        Movie.certificate).filter_by(id=movie_id).first().certificate)
    email_address = (Ticket.query.with_entities(
        Ticket.email).order_by(Ticket.id.desc()).first()).email
    
    id_required = False
    if certificate == "12A" or certificate == "12" or certificate == "15" or certificate == "18":
        id_required = True
    
    name = Movie.query.with_entities(
        Movie.name).filter_by(id=movie_id).first().name
    
    sale = Sale.query.order_by(Sale.id.desc()).first()
    sale_id = sale.id
    price = sale.price
    tos = sale.time_of_sale

    filename = "ticket_" + str(last_ticket_dict["id"]) + ".pdf"
    pdf = canvas.Canvas(filename)
    pdf.setTitle("ticket_" + str(last_ticket_dict["id"]))

    pdf.setFont("Helvetica", 16)
    pdf.drawCentredString(270, 770, "Arena Cinema")
    pdf.setFont("Helvetica", 12)
    pdf.drawCentredString(270, 755, "Albion Street")
    pdf.setFont("Helvetica", 10)
    pdf.drawCentredString(270, 745, "Leeds")

    pdf.setFont("Courier-Bold", 32)
    pdf.drawCentredString(270, 710, name)
    pdf.setFont("Courier-Bold", 14)
    if not id_required:
        pdf.drawCentredString(270, 690, certificate)
    else:
        pdf.drawString(180, 690, certificate)

Project/templates/base.html
<!DOCTYPE html>

<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<title>{% if title %}{{ title }} - Arena Cinema{% else %}Welcome to Arena Cinema{% endif %}</title>
<link rel="shortcut icon" href="../static/favicon.ico">

<body>
	<nav class="navbar navbar-expand-lg text-white bg-dark">
		<a class="navbar-brand" style="color: white;" href={{url_for("users.display_movies")}}>Arena Cinema</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
			aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
			<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
				<li class="nav-item active">
					<a class="nav-link" style="color: white;" href={{url_for("users.display_movies")}}>What's on<span
							class="sr-only">(current)</span></a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if current_user.is_anonymous %}
				<li><a style="color: white;" href={{url_for("users.register")}}>Register</a></li>
				<li style="padding-left: 15px;"><a style="color: white;" href={{url_for("users.login")}}>Login</a></li>
				{% else %}
				<li><b>Hello, {{current_user.username}}!</b></li>
				<li style="padding-left: 15px;"><a style="color: white;" href={{url_for("users.logout")}}>Logout</a></li>
				{% endif %}
			</ul>
		</div>
	</nav><br>
	{% block content %}
	<div class="container">
		{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
		{% for category, message in messages %}
		<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
			<span>{{ message }}</span>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		{% endfor %}
		{% endif %}
		{% endwith %}
		{% block app_content %}{% endblock %}
	</div>
	{% endblock %}
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
		integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
		crossorigin="anonymous"></script>
</body>

Project/templates/business_base.html
<!DOCTYPE html>

<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<title>{% if title %}{{ title }} - Arena Cinema{% else %}Arena Cinema Business{% endif %}</title>
<link rel="shortcut icon" href="../static/favicon.ico">

<body>
	<nav class="navbar navbar-expand-lg navbar-light text-white bg-dark">
		<a class="navbar-brand" style="color: white;" href={{url_for("business.display_movies")}}>Arena Cinema Business</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
			aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
			<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
				<li class="nav-item active">
					<a class="nav-link" style="color: white;" href={{url_for("business.display_movies")}}>Make Bookings<span
							class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" style="color: white;" href={{url_for("business.movie_details")}}>Add Movies<span
							class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" style="color: white;" href={{url_for("business.all_movies")}}>Add Screenings<span
							class="sr-only">(current)</span></a>
				</li>
				{% if current_user.is_manager == 1 %}
				<li class="nav-item active">
					<a class="nav-link" style="color: white;" href={{url_for("owner.income")}}>View Income<span
							class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" style="color: white;" href={{url_for("owner.compare_movies")}}>Compare Ticket Sales<span
							class="sr-only">(current)</span></a>
				</li>
				{% endif %}
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if current_user.is_anonymous %}
				<li><a style="color: white;" href={{url_for("business.login")}}>Login</a></li>
				{% else %}
				<li><b>Hello, {{current_user.username}}!</b></li>
				<li style="padding-left: 15px;"><a style="color: white;" href={{url_for("business.logout")}}>Logout</a></li>
				{% endif %}
			</ul>
		</div>
	</nav><br>
	{% block content %}
	<div class="container">
		{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
		{% for category, message in messages %}
		<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
			<span>{{ message }}</span>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		{% endfor %}
		{% endif %}
		{% endwith %}
		{% block app_content %}{% endblock %}
	</div>
	{% endblock %}
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
		integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
		integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
		crossorigin="anonymous"></script>
</body>

Project/templates/business_list.html
{% extends "business_base.html" %}
{% block app_content %}
<div class="container">
	<div class="jumbotron" style="padding-bottom: 20px; padding-top: 20px;">
		<h1 style="font-weight: 400;" class="display-4 text-center">Arena Cinema</h1>
		<p class="lead text-center" style="font-weight: 400;">Albion Street, Leeds</p>
		<hr class="my-4">
		<p class="lead text-center" style="font-weight: 450;">Watch the latest films in the centre of town</p>
	</div>
	<form style="padding-bottom: 15px;" method="POST">
		<div class="input-group">
			<div class="form-outline col-sm-11">
				{{ form.csrf_token }}
				{{ form.search(class='form-control',
				placeholder='Search', form_type="inline", style="width:100%") }}
			</div>
			<button type="submit" class="btn btn-primary" style="width: 7%;">
				<i class="bi bi-search"></i></button>
			</button>
		</div>
	</form>

	{% for movie in list_movies %}

	<div class="card text-white bg-dark mb-3">
		<div class="card-header">
			<h1 style="font-size:60px">{{movie.name}}</h1>
		</div>
		<div class="card-body">
			<img class="col-4" src="{{ url_for('static' , filename = movie.image_path) }}"
				style="max-width:auto; max-height:50%; float:right">
			<ul class="list-group list-group-flush col-8">
				<li class="list-group-item" style="background:#343a40;">
					<p style="font-size:28px">{{movie.blurb}}</p>
				</li>
				<li class="list-group-item" style="background:#343a40;">
					<p style="font-size:24px">{{movie.actors}}</p>
				</li>
				<li class="list-group-item" style="background:#343a40;">
					<h5>Certificate: {{movie.certificate}}</h5>
				</li>
				<li class="list-group-item" style="background:#343a40;">
					<h5>Price: {{movie.price_as_pence | currency_format}}</h5>
				</li>
				<br>
				<div class="row">
					{% for screenings in list_screenings %}
					{% if screenings.screened_movie.id == movie.id %}
					<div class="card text-white bg-secondary text-center" style="background:#343a40;margin: 10px;">
						<div class="card-body">
							<h5>Time: {{screenings.time.strftime('%H:%M')}}</h5>
							<h5>Date: {{screenings.date.strftime('%d-%m-%Y')}}</h5>
							<a href="./seats_for_screening/{{screenings.id}}"><button type="button"
									class="btn btn-success btn-sm">Book
									now</button></a>
						</div>
					</div>
					<br>
					{% endif %}
					{% endfor %}
				</div>
			</ul>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

Project/templates/buy_ticket.html
{% extends "business_base.html" %}
{% block app_content %}
<div class="container text-center">
	<div class="card bg-dark text-white mb-3">
		<div class="card-header">
			<h1>Buy Ticket for: {{movie.name}}</h1>
			<h5>Playing on: {{screening.date.strftime('%d/%m/%Y')}}, at {{screening.time.strftime('%H:%M')}}</h5>
		</div>
		<div class="card-body">
			<form method="POST">
				{{form.hidden_tag()}}
				{{ form.csrf_token }}
				<div class="form-group">
					{{form.first_name(class = "form-control", placeholder="First name")}}
				</div>
				<div class="form-group">
					{{form.last_name(class = "form-control", placeholder="Last name")}}
				</div>
				<div class="form-group">
					{{form.email(class = "form-control", placeholder="Email")}}
				</div>
				<div class="form-group">
					{{form.age(class = "form-control", placeholder=" Enter Age")}}
				</div>
				<div class="alert alert-primary" role="alert">
					Price: <b>{{price | currency_format}}</b> {% if is_vip %} (VIP) {% endif %}
				</div>
				<div class="alert alert-dark" role="alert">
					Note: 10% discount for People over 64 years </div>
				<div class="form-group">
					{{form.submit(class="btn btn-primary")}}
				</div>
				<div class="form-check">
					<div>
						{{form.pay_by_card(class="form-check-input")}} {{form.pay_by_card.label}}?
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

Project/templates/buy_ticket_online.html
{% extends "base.html" %}
{% block app_content %}
<div class="container text-center">
	<div class="card bg-dark text-white mb-3">
		<div class="card-header">
			<h1>Buy Ticket for: {{movie.name}}</h1>
			<h5>Playing on: {{screening.date.strftime('%d/%m/%Y')}}, at {{screening.time.strftime('%H:%M')}}</h5>
		</div>
		<div class="card-body">
			<form method="POST">
				{{form.hidden_tag()}}
				{{ form.csrf_token }}
				<div class="form-group">
					{{form.first_name(class = "form-control", placeholder="First name")}}
				</div>
				<div class="form-group">
					{{form.last_name(class = "form-control", placeholder="Last name")}}
				</div>
				<div class="form-group">
					{{form.email(class = "form-control", placeholder="Email")}}
				</div>
				<div class="form-group">
					{{form.age(class = "form-control", placeholder=" Enter Age")}}
				</div>
				<div class="alert alert-primary" role="alert">
					Price: <b>{{price | currency_format}}</b> {% if is_vip %} (VIP) {% endif %}
				</div>
				<div class="alert alert-dark" role="alert">
					Note: 10% discount for People over 64 years </div>
				<div class="form-group">
					{{form.submit(class="btn btn-primary")}}
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

Project/templates/card_payment.html
{% extends "base.html" %}
{% block app_content %}
<div class="container">
	<div class="card border-0 shadow my-5">
		<div class="card-body p-15">
			<h1>
				<p class="text-info">Card Payment</p>
			</h1>
			<hr />
			<form method="POST">
				{{form.hidden_tag()}}
				{{ form.csrf_token }}
				{{form.name(class="form-control", placeholder="Name")}}<br>
				{{form.card_number(class="form-control", placeholder="Card number")}}<br>
				{{form.expiration(class="form-control", placeholder="Expiration date")}}<br>
				{{form.security_code(class="form-control", placeholder="Security code")}}<br><br>
				{{form.address(class="form-control", placeholder="Address")}}<br>
				{{form.town_city(class="form-control", placeholder="Town/City")}}<br>
				{{form.postcode(class="form-control", placeholder="Postcode")}}<br>
				{{form.country(class="form-control", placeholder="Country")}}<br>
				<button type="submit" class="btn btn-primary">Submit</button>
				<hr />
				{% if (current_user.is_authenticated and not current_user.is_staff == 1) %}
				{{ form.remember_me }} Remember Me
				{% endif %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

Project/templates/compare.html
{% extends "business_base.html" %}
{% block app_content %}
<div class="container text-center">
	<div class="card text-center">
		<div class="card-header">
			<h2>Weekly sales summary</h2>
		</div>
		<div class="card-body">
			<img src='../static/sales.png?dummy={{ current_datetime_string }}' class="img-fluid">
		</div>
		<div class="card-footer text-muted">
			Last updated: {{current_datetime.strftime('%d-%m-%Y %H:%M:%S')}}
		</div>
	</div>
</div>
{% endblock %}

Project/templates/login.html
{% extends 'base.html' %}
{% block app_content %}

<body>
	<h1 class="text-center">Login to Arena Cinema</h1>
	<div class="container-fluid h-100">
		<div class="row justify-content-center align-items-center h-100">
			<div class="col col-sm-6 col-md-6 col-lg-4 col-xl-5">
				<form method="POST">
					{{ form.csrf_token }}
					<div class="form-group">
						{{form.username(class="form-control", style="width:100%;", placeholder="Username")}}
					</div>
					<div class="form-group">
						{{form.password(class="form-control", style="width:100%;", placeholder="Password")}}
					</div>
					<div class="form-group">
						{{form.submit(class="btn btn-primary", style="width:100%")}}
					</div>
				</form>
				<a href={{url_for("users.register")}}>Create an account</a>
			</div>
		</div>
	</div>
</body>
{% endblock %}